### ISSUE TITLE
Build the app before package it

### ISSUE THREAD

**Issue by saadbinsaeed** [rot1024/electron-react-webpack-boilerplate#2]
If i do not build the app and package it, app do not works. Even nothing shows up when i double clicked on app icon but if i build the before packaging it, it works very fine. App run smoothly. I am not sure why this is happening.

**Comment by rot1024** [comment]
It is no problem. You have to build the app before package the app, because output of building the app are used for packaging the app.

**Comment by saadbinsaeed** [comment]
OK just a little query, I am not able to load resources in my production package. For the dev server i managed to load them by adding the content base property to webpack.devServer but for the production package they are not loaded. In case of production build publicPath remains undefined.
```
output: {
      filename: electronMain ? "index.js" : "bundle.js",
      libraryTarget: "commonjs2",
      path: path.resolve(__dirname, "build"),
      publicPath: electronRenderer && !prod ? `http://localhost:${PORT}/build/` : undefined,
    },
```
I am presuming that this is the cause of the problem that i am not able to load images in my production package, Any Help?

**Comment by rot1024** [comment]
You can include any assets by putting them in `resources` directory. Any files in the `resources` directory will be copied.

For example: you can load `resources/image.png` as follow.

```
<img src="resources/image.png" />
```

This image will be shown in both development env and production env.

**Comment by saadbinsaeed** [comment]
Actually i don't want to change the path of the resources, they should be same in web and desktop application. Solved it by copyPlugin of webpack. Thanks for your help.
